name: Simple Flask Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_DEFAULT_REGION: us-east-1
      TF_IN_AUTOMATION: true

    steps:
      # 1. Checkout code
      - uses: actions/checkout@v4

      # 2. Setup Terraform
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0

      # 3. Terraform Init
      - name: Terraform Init
        working-directory: terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform init -input=false

      # 4. Terraform Apply (NO approval)
      - name: Terraform Apply
        working-directory: terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform apply -auto-approve

      # 5. Get EC2 public IP
      - name: Get EC2 IP
        id: ec2
        working-directory: terraform
        run: echo "ip=$(terraform output -raw ec2_public_ip)" >> $GITHUB_OUTPUT

      # 6. Deploy Flask app to EC2 (SIMPLE)
      - name: Deploy Flask app
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ steps.ec2.outputs.ip }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo apt update
            sudo apt install -y python3-pip git

            cd /home/ubuntu
            rm -rf flask-devops-ci
            git clone https://github.com/Shree0211/flask-devops-ci.git
            cd flask-devops-ci

            pip3 install -r requirements.txt
            pkill -f app.py || true
            nohup python3 app.py > app.log 2>&1 &
